### ISSUE TITLE
Support for text-decoration-color

### ISSUE THREAD

**Issue by kerns** [benface/tailwindcss-typography#18]
Would be nice to see `text-decoration-color` supported. This is useful for example when striking text, to have the strike color different from the underlying text color.

Could also be helpful/applicable to something more common like link underlines? But I have not tested (or needed) that.

**Comment by benface** [comment]
I should probably add support for [`text-decoration-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style) as well.

**Comment by kerns** [comment]
That would make sense and be great.

**Comment by benface** [comment]
Thank you, text decoration style and color utilities have been added in [v3.1.0](https://github.com/benface/tailwindcss-typography/releases/tag/v3.1.0).
