### ISSUE TITLE
Font Size + Line Height

### ISSUE THREAD

**Issue by bymayo** [benface/tailwindcss-typography#19]
When using something like:

`fontSize: theme('fontSize.2xl')`

And the settings for that font size are:

`'2xl': ['1.875rem', '1.2']`

It outputs:

`font-size: 1.875rem,1.2;`

Is there anyway to make this work better with 1.3.0 and line heights? https://tailwindcss.com/docs/font-size/#providing-a-default-line-height-v1-3-0

**Comment by benface** [comment]
Thank you, this has been fixed in [v3.1.0](https://github.com/benface/tailwindcss-typography/releases/tag/v3.1.0).
