### ISSUE TITLE
Support Tailwind v2

### ISSUE THREAD

**Issue by arafatamim** [benface/tailwindcss-typography#28]
Currently it throws an error after upgrading to Tailwind v2.0.2:
~~`TypeError: target is not a function`~~
Edit: Sorry, that error was related to another plugin `tailwindcss-gap`. This one throws `PostCSS plugin postcss-nested requires PostCSS 8.`

**Comment by benface** [comment]
Hey @arafatamim, thank you for reporting. I actually decided to deprecate both `tailwindcss-gap` and this one. They are simply not needed anymore. Please read the note at the top of the [`README`](https://github.com/benface/tailwindcss-typography#readme) (and [here](https://github.com/benface/tailwindcss-gap#readme) is the one for `tailwindcss-gap`). Thanks!
