### ISSUE TITLE
Not working with @screen in TW 2

### ISSUE THREAD

**Issue by Kcko** [benface/tailwindcss-typography#30]
Code:

```
theme: {
		textStyles: theme => ({
			heading: {
				output: false, // this means there won't be a "heading" component in the CSS, but it can be extended
				fontWeight: theme('fontWeight.bold'),
				lineHeight: theme('lineHeight.tight'),
			},

			h5: {
				extends: 'heading',
				fontSize: theme('fontSize.4xl'),
				'@screen md': {
					fontSize: theme('fontSize.3xl'),
				},
				'@screen sm': {
					fontSize: theme('fontSize.2xl'),
				},
			},
			h6: {
				extends: 'heading',
				fontSize: theme('fontSize.xl'),
			},
		})
```

And output is ![SCREEN](https://bit.ly/3scON0D)[]

How to solve it? 
is this plugin still maintained?

**Comment by benface** [comment]
> is this plugin still maintained?

It's not abandoned but not actively maintained at the moment, as I haven't had a need for this plugin in a while. It definitely should work with Tailwind 2 though, so I'll try to fix this bug soon. If you need it sooner, PRs are more than welcome!

**Comment by Kcko** [comment]
Thx for answer. Ur plugin has more better config, more readable for me than official tailwind typo plugin.
I hope that you solve in future :-)

Thx for fast answer.

**Comment by benface** [comment]
Hey @Kcko, I'm sorry but in the end, I decided to deprecate this plugin. I clearly don't have time to maintain it anymore, and Tailwind has added support for most of its features. It's only a matter of time for the rest of them. Please read the note at the top of the [`README`](https://github.com/benface/tailwindcss-typography#readme). Thanks!
