### ISSUE TITLE
Bug: prose lists in firefox

### ISSUE THREAD

**Issue by paulocastellano** [benface/tailwindcss-typography#43]
In Firefox 96.0.1 I have this problem on Mac and Windows.

In chrome works well!

<img width="156" alt="Screen Shot 2022-01-17 at 13 50 11" src="https://user-images.githubusercontent.com/265964/149809811-467035e7-bba3-4a87-b93e-e8a9c609032e.png">

**Comment by benface** [comment]
Hey @paulocastellano! That's weird, but I doubt this plugin is causing it. I would try to find the simplest reproducible case (you can probably narrow it down to a single CSS property or way of structuring the HTML) and report it to Firefox.

In any case, I'm sorry but I am deprecating this plugin. Please read the note at the top of the [`README`](https://github.com/benface/tailwindcss-typography#readme). Thanks!
